=== UO294013/sew/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud_circuito" />
				<xs:element ref="anchura_media" />
				<xs:element ref="fecha_2025" />
				<xs:element ref="hora_carrera_españa" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas_inicio" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacion_mundial" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="vueltas" type="xs:integer" use="required" />
			<xs:attribute name="localidad_proxima" type="xs:string" use="required" />
			<xs:attribute name="pais" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud_circuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudBase">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- Tipo simple para poder añadir restricciones y unidades a la vez -->
	<xs:simpleType name="longitudBase">
		<xs:restriction base="xs:integer">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Fin del tipo simple para longitud -->
	<xs:element name="anchura_media">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="anchuraBase">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- Tipo simple para poder añadir restricciones y unidades a la vez -->
	<xs:simpleType name="anchuraBase">
		<xs:restriction base="xs:integer">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Fin del tipo simple para anchura -->
	<xs:element name="fecha_2025" type="xs:date" />
	<xs:element name="hora_carrera_españa" type="xs:time" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas_inicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" >
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-180.0"/>
				<xs:maxInclusive value="180.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="latitud" >
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-90.0"/>
				<xs:maxInclusive value="90.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="altitudBase">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- Tipo simple para poder añadir restricciones y unidades a la vez -->
	<xs:simpleType name="altitudBase">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.0"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Fin del tipo simple para altitud -->
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenada" />
			</xs:sequence>
			<xs:attribute name="sector" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaBase">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- Tipo simple para poder añadir restricciones y unidades a la vez -->
	<xs:simpleType name="distanciaBase">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0.0"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Fin del tipo simple para altitud -->
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto" type="xs:string" />
	<xs:element name="tiempo" type="xs:time" />
	<xs:element name="clasificacion_mundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO294013/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es circuito.xsd" nombre="Le Mans" vueltas="27" localidad_proxima="Le Mans" pais="Francia">
    <longitud_circuito unidad="metros">4187</longitud_circuito>
    <anchura_media unidad="metros">13</anchura_media>
    <fecha_2025>2025-05-11</fecha_2025>
    <hora_carrera_españa>14:00:00</hora_carrera_españa>
    <patrocinador>Michelin</patrocinador>
        <referencias>
            <referencia>https://www.motogp.com/es/calendar/2025/event/france/e9b386c5-9d95-405e-880e-7d9105ce1cbe?tab=overview</referencia>
            <referencia>https://es.wikipedia.org/wiki/Gran_Premio_de_Francia_de_Motociclismo</referencia>
            <referencia>https://www.dazn.com/es-ES/news/motor/circuito-le-mans-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-francia-mundial-motogp/1ds4qyf2z4y5wz5uatyt4s8lh</referencia>
            <referencia>https://es.motorsport.com/motogp/news/mundiales-motogp-2025-puntos-posiciones-francia/10721575/</referencia>
        </referencias>
        <fotos>
            <foto>multimedia/lemans_aereo.jpg</foto>
            <foto>multimedia/lemans_meta.jpg</foto>
            <foto>multimedia/lemans_tramos.jpg</foto>
        </fotos>
        <videos>
            <video>multimedia/lemans.mp4</video>
            <video>multimedia/zarco.mp4</video>
        </videos>
        <coordenadas_inicio>
            <coordenada>
                <longitud>0.2075998</longitud>
                <latitud>47.9511720</latitud>
                <altitud unidad="metros">53.68</altitud>
            </coordenada>
        </coordenadas_inicio>
        <tramos>
            <tramo sector="1">
                <distancia unidad="metros">175.47</distancia>
                <coordenada>
                    <longitud>0.2076845</longitud>
                    <latitud>47.9527561</latitud>
                    <altitud unidad="metros">56.06</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">65.57</distancia>
                <coordenada>
                    <longitud>0.2077719</longitud>
                    <latitud>47.9533405</latitud>
                    <altitud unidad="metros">57.30</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">115.61</distancia>
                <coordenada>
                    <longitud>0.2081108</longitud>
                    <latitud>47.9543599</latitud>
                    <altitud unidad="metros">60.72</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">67.97</distancia>
                <coordenada>
                    <longitud>0.2084193</longitud>
                    <latitud>47.9549459</latitud>
                    <altitud unidad="metros">63.52</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">52.08</distancia>
                <coordenada>
                    <longitud>0.2087131</longitud>
                    <latitud>47.9553673</latitud>
                    <altitud unidad="metros">65.77</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">50.94</distancia>
                <coordenada>
                    <longitud>0.2091662</longitud>
                    <latitud>47.9557153</latitud>
                    <altitud unidad="metros">67.95</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">156.17</distancia>
                <coordenada>
                    <longitud>0.2109462</longitud>
                    <latitud>47.9564535</latitud>
                    <altitud unidad="metros">74.30</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">21.83</distancia>
                <coordenada>
                    <longitud>0.2110410</longitud>
                    <latitud>47.9566379</latitud>
                    <altitud unidad="metros">75.52</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">46</distancia>
                <coordenada>
                    <longitud>0.2109203</longitud>
                    <latitud>47.9570365</latitud>
                    <altitud unidad="metros">78.24</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">22.87</distancia>
                <coordenada>
                    <longitud>0.2110802</longitud>
                    <latitud>47.9572076</latitud>
                    <altitud unidad="metros">79.12</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">165.75</distancia>
                <coordenada>
                    <longitud>0.2129530</longitud>
                    <latitud>47.9580023</latitud>
                    <altitud unidad="metros">80.85</altitud>
                </coordenada>
            </tramo>
            <tramo sector="1">
                <distancia unidad="metros">38.85</distancia>
                <coordenada>
                    <longitud>0.2133147</longitud>
                    <latitud>47.9582415</latitud>
                    <altitud unidad="metros">79.89</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">70.80</distancia>
                <coordenada>
                    <longitud>0.2138827</longitud>
                    <latitud>47.9587447</latitud>
                    <altitud unidad="metros">76.87</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">55.84</distancia>
                <coordenada>
                    <longitud>0.2144339</longitud>
                    <latitud>47.9590757</latitud>
                    <altitud unidad="metros">73.21</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">37.64</distancia>
                <coordenada>
                    <longitud>0.2149427</longitud>
                    <latitud>47.9591195</latitud>
                    <altitud unidad="metros">70.58</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">46.49</distancia>
                <coordenada>
                    <longitud>0.2155021</longitud>
                    <latitud>47.9589275</latitud>
                    <altitud unidad="metros">68.33</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">43.94</distancia>
                <coordenada>
                    <longitud>0.2156786</longitud>
                    <latitud>47.9585480</latitud>
                    <altitud unidad="metros">67.67</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">42.20</distancia>
                <coordenada>
                    <longitud>0.2154957</longitud>
                    <latitud>47.9581805</latitud>
                    <altitud unidad="metros">68.70</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">89.08</distancia>
                <coordenada>
                    <longitud>0.2147220</longitud>
                    <latitud>47.9575653</latitud>
                    <altitud unidad="metros">71.58</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">179.50</distancia>
                <coordenada>
                    <longitud>0.2128730</longitud>
                    <latitud>47.9565480</latitud>
                    <altitud unidad="metros">72.14</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">49.45</distancia>
                <coordenada>
                    <longitud>0.2124487</longitud>
                    <latitud>47.9562141</latitud>
                    <altitud unidad="metros">71.23</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">31.62</distancia>
                <coordenada>
                    <longitud>0.2124465</longitud>
                    <latitud>47.9559397</latitud>
                    <altitud unidad="metros">70.37</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">36.04</distancia>
                <coordenada>
                    <longitud>0.2127516</longitud>
                    <latitud>47.9556941</latitud>
                    <altitud unidad="metros">69.41</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">57.60</distancia>
                <coordenada>
                    <longitud>0.2135153</longitud>
                    <latitud>47.9557001</latitud>
                    <altitud unidad="metros">68.03</altitud>
                </coordenada>
            </tramo>
            <tramo sector="2">
                <distancia unidad="metros">57.70</distancia>
                <coordenada>
                    <longitud>0.2142224</longitud>
                    <latitud>47.9559049</latitud>
